package com.kerem.phinance.service;

import com.kerem.phinance.dto.TransactionDto;
import com.kerem.phinance.model.Transaction;
import com.kerem.phinance.repository.TransactionRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.springframework.cglib.core.Local;

@Slf4j
@Service
@RequiredArgsConstructor
public class RecurringTransactionScheduler {

    private final TransactionRepository transactionRepository;
    private final TransactionService transactionService;

    // Run every day (86,400,000 milliseconds = 1 day)
    @Scheduled(fixedRate = 86_400_000)
    public void processRecurringTransactions() {
        log.info("Starting recurring transactions processing...");

        List<Transaction> recurringTransactions = transactionRepository.findByRecurringTrue();
        YearMonth currentMonth = YearMonth.now();
        DateTimeFormatter monthFormatter = DateTimeFormatter.ofPattern("MMMM yyyy");

        int processed = 0;
        int created = 0;

        for (Transaction transaction : recurringTransactions) {
            try {
                processed++;

                YearMonth transactionMonth = YearMonth.from(transaction.getDate());

                // Skip if transaction is in current or future month
                if (!transactionMonth.isBefore(currentMonth)) {
                    continue;
                }

                // Skip if transaction date + 1 month is not passed yet
                LocalDate nextTransactionDate = transaction.getDate().plusMonths(1);
                if (nextTransactionDate.isAfter(LocalDate.now())) {
                    continue;
                }

                boolean whileBreaked = false;
                // If the transaction is more than 1 month old, we should create transactions for all missed months until current month
                while (transactionMonth.plusMonths(1).isBefore(currentMonth)) {
                    transactionMonth = transactionMonth.plusMonths(1);
                    LocalDate missedTransactionDate = transaction.getDate().withYear(transactionMonth.getYear()).withMonth(transactionMonth.getMonthValue());

                    // Generate the new transaction name with missed month
                    String missedMonthName = transactionMonth.format(monthFormatter);
                    String missedTransactionName = transaction.getDescription() + " " + missedMonthName;

                    // Check if a transaction with this name and amount already exists for this user
                    boolean exists = transactionRepository.findByUserIdAndDateBetween(
                            transaction.getUserId(),
                            missedTransactionDate.withDayOfMonth(1),
                            missedTransactionDate.withDayOfMonth(missedTransactionDate.lengthOfMonth())
                    ).stream().anyMatch(t
                            -> t.getDescription().equals(missedTransactionName)
                            && t.getAmount().compareTo(transaction.getAmount()) == 0
                    );

                    if (exists) {
                        continue;
                    }

                    // Create a new transaction for the missed month
                    TransactionDto missedTransactionDto = new TransactionDto();
                    missedTransactionDto.setAccountId(transaction.getAccountId());
                    missedTransactionDto.setType(transaction.getType());
                    missedTransactionDto.setAmount(transaction.getAmount());
                    missedTransactionDto.setCategoryId(transaction.getCategoryId());
                    missedTransactionDto.setDescription(missedTransactionName);
                    missedTransactionDto.setDate(missedTransactionDate);
                    missedTransactionDto.setRecurring(false);
                    missedTransactionDto.setRecurrencePattern(null);
                    missedTransactionDto.setAutoGenerated(true);
                    missedTransactionDto.setTransferToAccountId(transaction.getTransferToAccountId());

                    transactionService.createTransaction(transaction.getUserId(), missedTransactionDto);
                    created++;
                    log.info("Created missed recurring transaction '{}' for user {}", missedTransactionName, transaction.getUserId());

                }

                // Skip if transaction day is not passed yet in current month
                LocalDate transactionDayThisMonth = transaction.getDate().withYear(currentMonth.getYear()).withMonth(currentMonth.getMonthValue());
                if (transactionDayThisMonth.isAfter(LocalDate.now())) {
                    continue;
                }

                // Generate the new transaction name with current month
                String currentMonthName = currentMonth.format(monthFormatter);
                String newTransactionName = transaction.getDescription() + " " + currentMonthName;

                // Check if a transaction with this name and amount already exists for this user
                boolean exists = transactionRepository.findByUserIdAndDateBetween(
                        transaction.getUserId(),
                        currentMonth.atDay(1),
                        currentMonth.atEndOfMonth()
                ).stream().anyMatch(t
                        -> t.getDescription().equals(newTransactionName)
                        && t.getAmount().compareTo(transaction.getAmount()) == 0
                );

                if (exists) {
                    continue;
                }

                // Create a new transaction for the current month
                TransactionDto newTransactionDto = new TransactionDto();
                newTransactionDto.setAccountId(transaction.getAccountId());
                newTransactionDto.setType(transaction.getType());
                newTransactionDto.setAmount(transaction.getAmount());
                newTransactionDto.setCategoryId(transaction.getCategoryId());
                newTransactionDto.setDescription(newTransactionName);
                LocalDate transactionDate = LocalDate.now().withDayOfMonth(transaction.getDate().getDayOfMonth());
                // If the transaction day does not exist in the current month (e.g., 30th in February), set it to the last day of the month
                if (transactionDate.getMonth() != currentMonth.getMonth()) {
                    transactionDate = currentMonth.atEndOfMonth();
                }
                newTransactionDto.setDate(transactionDate); // Use transaction day of current month
                newTransactionDto.setRecurring(false); // Not a recurring transaction
                newTransactionDto.setRecurrencePattern(null);
                newTransactionDto.setAutoGenerated(true);
                newTransactionDto.setTransferToAccountId(transaction.getTransferToAccountId());

                transactionService.createTransaction(transaction.getUserId(), newTransactionDto);
                created++;
                log.info("Created recurring transaction '{}' for user {}", newTransactionName, transaction.getUserId());

            } catch (Exception e) {
                log.error("Error processing recurring transaction {}: {}", transaction.getId(), e.getMessage());
            }
        }

        log.info("Recurring transactions processing completed. Processed: {}, Created: {}", processed, created);
    }
}
